language: bash

services:
  - docker

before_script:
  - make image tag=$TRAVIS_BRANCH

script:
  - make test tag=$TRAVIS_BRANCH

deploy:
  provider: script
  script: make release tag=$TRAVIS_TAG
  on:
    tags: true
